global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:


  - job_name: 'primary-backend'
    static_configs:
      - targets: ['192.168.0.104:4080']


  - job_name: 'workflow-service'
    static_configs:
      - targets: ['192.168.0.104:4040']


  - job_name: 'pushgateway'
    honor_labels: true   
    static_configs:
      - targets: ["192.168.0.104:9091"]


  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.0.104:9090']
