scrape_configs:
  - job_name: 'api-services'
    static_configs:
      - targets:
          - 'api-1:3000'
          - 'api-2:3000'

  - job_name: 'pushgateway'
    static_configs:
      - targets:
          - 'pushgateway:9091'
